### ISSUE TITLE
syntax error in ./ncp.py

### ISSUE THREAD

**Issue by mikemakaroff** [walthowd/husbzb-firmware#1]
i am running docker run --device=/dev/ttyUSB1:/dev/ttyUSB1 -it walthowd/husbzb-firmware bash
root@e72525a1e48d:/tmp/silabs# ./ncp.py scan
  File "./ncp.py", line 211
    return ERROR_NCP_WRONG_EZSP_VERSION
looks like a result of recent change

**Comment by jcbbas** [comment]
Looks like I am having the same issue as well.

**Comment by walthowd** [comment]
Should be fixed here:

https://github.com/walthowd/husbzb-firmware/commit/36717188495ff7284e1e90ed7028ba323a1bec67

**Comment by jcbbas** [comment]
Awesome thank you! Working great now!
